services:
  # signal-server:
  #   build: .
  #   container_name: signal-server
  #   depends_on:
  #     - datadog
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

  datadog:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=4c3165fcb406d26a9678c81db9a423f2 # Your Datadog API key
      - DD_SITE=datadoghq.eu # For US datacenter
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true # Enable APM
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true # Allow StatsD traffic from other containers
      - DD_ENV=staging # match environment setting from config
      - DD_SERVICE=chat # match service from metrics tag
    ports:
      - "8125:8125/udp" # StatsD intake
      - "10516:10516/tcp" # For logstashtcpsocket destination in config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
